// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_4LcJqkyI8rPBU4jPRWFTNmiCQTRRls8',
    appId: '1:444406023971:web:9a12a3e24489e4e4872e96',
    messagingSenderId: '444406023971',
    projectId: 'shmazumder-23',
    authDomain: 'shmazumder-23.firebaseapp.com',
    storageBucket: 'shmazumder-23.appspot.com',
    measurementId: 'G-X17DM196DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo215TRl_Nkdp1t0m48C6rda_c9vRD_E4',
    appId: '1:444406023971:android:53c8343c4d46ca7b872e96',
    messagingSenderId: '444406023971',
    projectId: 'shmazumder-23',
    storageBucket: 'shmazumder-23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWbGOi8FdnOFZdS3t9O9uV5o0acuIBsV8',
    appId: '1:444406023971:ios:4974933314f3df32872e96',
    messagingSenderId: '444406023971',
    projectId: 'shmazumder-23',
    storageBucket: 'shmazumder-23.appspot.com',
    androidClientId: '444406023971-54bqjl4m6ci98o1eeo02mhj8f01q7642.apps.googleusercontent.com',
    iosClientId: '444406023971-75h89cf2pgibksp8db4kjjc4fhch2bve.apps.googleusercontent.com',
    iosBundleId: 'com.example.instoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWbGOi8FdnOFZdS3t9O9uV5o0acuIBsV8',
    appId: '1:444406023971:ios:4974933314f3df32872e96',
    messagingSenderId: '444406023971',
    projectId: 'shmazumder-23',
    storageBucket: 'shmazumder-23.appspot.com',
    androidClientId: '444406023971-54bqjl4m6ci98o1eeo02mhj8f01q7642.apps.googleusercontent.com',
    iosClientId: '444406023971-75h89cf2pgibksp8db4kjjc4fhch2bve.apps.googleusercontent.com',
    iosBundleId: 'com.example.instoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzabeuiqUUunpTwgpyugu0Co6HkhhmApI',
    appId: '1:444406023971:web:3a53fe8b73c404e6872e96',
    messagingSenderId: '444406023971',
    projectId: 'shmazumder-23',
    authDomain: 'shmazumder-23.firebaseapp.com',
    storageBucket: 'shmazumder-23.appspot.com',
    measurementId: 'G-L8FJ5436FN',
  );
}
